require: rubocop-rails

AllCops:
  SuggestExtensions: false
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'app/services/comparison_report_calculator.rb'
Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
